apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - appName: aspnet-core
        chart: aspnet-core
        targetRevision: 6.2.3
        environment: dev
      - appName: nginx
        chart: nginx
        targetRevision: 15.9.0
        environment: dev
      - appName: spark
        chart: nginx
        targetRevsion: 15.9.0
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      sources:
        - chart: '{{chart}}'
          repoURL: registry-1.docker.io/bitnamicharts
          targetRevision: '{{targetRevision}}'
          helm:
            releaseName: "{{appName}}"
            valueFiles:
            - $values/values/{{environment}}/{{appName}}/values.yaml
        - repoURL: 'https://github.com/claudegamboa/argocdsetup.git'
          targetRevision: HEAD
          ref: values

      destination:
        name: 'in-cluster'
        namespace: blueocean
      
      syncOptions:
        - CreateNamespace=true