apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - appName: aspnet-core
        chart: aspnet-core
        targetRevision: 6.2.3
      # - cluster: engineering
      #   url: in-cluster
      #   env: dev
      # - cluster: engineering-prod
      #   url: https://2.4.6.8
      # - cluster: finance-preprod
      #   url: https://9.8.7.6
      
        
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        chart: '{{.chart}}'
        repoURL: registry-1.docker.io/bitnamicharts  # note: the oci:// syntax is not included.
        targetRevision: '{{.targetRevision}}'
        # helm:
        #   # Release name override (defaults to application name)
        #   releaseName: "{{.appName}}"
        #   valueFiles:
        #   - "../values/{{.appName}}/values.yaml"
      destination:
        name: 'in-cluster'
        namespace: '{{.appName}}'
      
      syncOptions:
        - CreateNamespace=true