apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      # - cluster: engineering
      #   url: in-cluster
      #   env: dev
      # - cluster: engineering-prod
      #   url: https://2.4.6.8
      # - cluster: finance-preprod
      #   url: https://9.8.7.6
        - appName: aspnet-core
          chart: aspnet-core
          targetRevision: 6.2.3
        
  template:
    metadata:
      name: '{{.appName}}'
    spec:
      project: default
      source:
        chart: '{{.chart}}'
        repoURL: registry-1.docker.io/bitnamicharts  # note: the oci:// syntax is not included.
        targetRevision: '{{.targetRevision}}'
      destination:
        name: "in-cluster"
        namespace: 'aspnet-core'
      
      syncOptions:
        - CreateNamespace=true